import Head from "next/head";
import Image from "next/image";
import { Box, Center, Heading, Text, Flex } from "@chakra-ui/react";
import FullBodyHealthCheckups from "@/components/FullBodyHealthCheckups";
import ShopByHealthConcerns from "@/components/ShopByHealthConcerns";
import { Profile } from "./profile";

import FeatureBrands from "@/components/FeatureBrands";

import HomeSlider from "@/components/homeSlider";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSlider />

      <Box align="center" p="50px">
        <Text as="b" fontSize="xl">
          Tata 1mg: India’s Leading Online Pharmacy & Healthcare Platform
        </Text>
      </Box>
      <Center p="100px">
        <Image
          src={
            "https://onemg.gumlet.io/marketing/29087450-0f25-4856-96fc-62f4ea81bbd3.png"
          }
          height={1000}
          width={2000}
          alt="caruausal"
        />
      </Center>
      <Text>Shop by health concerns</Text>
      <ShopByHealthConcerns />

      <Text>Featured brands</Text>
      <FeatureBrands />

      <Text>Full body health checkups</Text>
      <FullBodyHealthCheckups />
      
      <Text>Pathology Tests | Up to 70% off</Text>
      <Text>Popular categories</Text>
      <Text>Popular Combo Deals</Text>
      <Text>Sugar substitutes</Text>
    </>
  );
}
