import React from 'react'
import {
    Box,
    Stack,
    Text,
    Image,
    Flex,
    Button,
    Heading,
} from "@chakra-ui/react";
import { AiFillStar } from 'react-icons/ai';
import Head from 'next/head';

const SingleProductPage = ({ data }) => {
    console.log(data);
    return (
        <>
            <Head>
                <title>Health Prime</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stack
                maxW="90%"
                direction={{ "lg": "row", "md": "column", "base": "column" }}
                m={{ "lg": "40px auto", "md": "30px auto", "base": "20px auto" }}
            >
                <Flex
                    w={{ "lg": "65%", "md": "100%", "base": "100%" }}
                    m="auto"
                    direction={{ "lg": "row", "md": "row", "base": "column" }}
                >
                    <Box
                        w={{ "lg": "50%", "md": "100%", "base": "100%" }}
                    >
                        <Image
                            m='auto'
                            src={data.src}
                            height={{ "lg": "300px", "md": "200px", "base": "150px" }}
                            alt=''
                        />
                    </Box>
                    <Box
                        w={{ "lg": "50%", "md": "100%", "base": "100%" }}
                        p={""}
                    >
                        <Text
                            fontSize={{ "lg": "24px", "md": "18px", "base": "16px" }}
                            mb={"10px"}
                            fontWeight={700}
                            lineHeight='35px'
                        >
                            {data.title}
                        </Text>
                        <Text
                            fontSize={{ "lg": "13px", "md": "12px", "base": "10px" }}
                            mb={"10px"}
                            color="#ff6f61"
                            fontWeight={600}
                        >
                            Tata 1mg Healthcare Solutions Private Limited
                        </Text>
                        <Flex gap={"20px"}>
                            <Button
                                bg="#1aab2a"
                                size={"xs"}
                                color={"#fff"}
                                fontSize={{ "lg": "13px", "md": "12px", "base": "10px" }}
                                mb={"10px"}
                                fontWeight={600}
                            >
                                {data.rating} <AiFillStar />
                            </Button>
                            <Text
                                fontSize={{ "lg": "13px", "md": "12px", "base": "10px" }}
                                mb={"10px"}
                                color="#ff6f61"
                                fontWeight={600}
                            >
                                {data.CardRatingDetail}
                            </Text>
                        </Flex>
                        <Text
                            color="grey"
                            fontSize={"18px"}
                            mb={"10px"}
                            fontWeight={600}>
                            {data.packsize}
                        </Text>
                        <Text
                            fontSize={{ "lg": "14px", "md": "12px", "base": "10px" }}
                            lineHeight='20px'
                            fontWeight={'400'}
                            textAlign={"justify"}
                            pb='15px' >
                            Product highlights <br />
                            • Lorem ipsum dolor sit amet consectetur adipisicing elit. <br />
                            • Exercitationem at nam tempora voluptatem error hic vitae. <br />
                            • excepturi iure nulla ducimus in. <br />
                            • Atque minima accusantium quibusdam.
                        </Text>
                    </Box>
                </Flex>
                <Box
                    minW={"25%"}
                    p={"10px 20px"}
                    h='150px'
                    borderRadius={'12px'}
                    boxShadow="rgba(99, 99, 99, 0.2) 0px 2px 8px 0px"
                >
                    <Heading
                        fontSize={{ "lg": "25px", "md": "20px", "base": "18px" }}
                        mb={"10px"}
                        fontWeight={600}
                    >
                        Price
                    </Heading>
                    <Box >
                        <Flex
                            gap={"10px"}
                            align="center"
                        >
                            <Text
                                fontSize={{ "lg": "25px", "md": "20px", "base": "18px" }}
                                mb={"10px"}
                                fontWeight={600}
                            >
                                ₹{data.price}
                            </Text>
                            <Text
                                color="grey"
                                fontSize={"15px"}
                                mb={"10px"}
                                textDecor="line-through"
                                fontWeight={600}
                            >
                                ₹{data["strike-price"]}
                            </Text>
                            <Text
                                fontSize={"15px"}
                                mb={"10px"}
                                color="#1aab2a"
                                bg='#edf9ee'
                                fontWeight={600}
                                p={"4px"}
                            >
                                {data["discount-percent"]}
                            </Text>
                        </Flex>
                    </Box>
                    <Button
                        w={"100%"}
                        size={"md"}
                        borderRadius="5px"
                        bg={"#ff6f61"}
                        _hover={{
                            bg: "#fd7c70",
                        }}
                        color="#fff"
                    >
                        Add To Cart
                    </Button>
                </Box>
            </Stack>
        </>
    )
}

export default SingleProductPage;

export async function getStaticPaths() {
    const res = await fetch(`https://dead-earrings-tick.cyclic.app/products`);
    let data = await res.json();
    return {
        paths: data.map((e) => (
            { params: { id: e.id.toString() } }
        )),
        fallback: false, 
    }
}

export async function getStaticProps(context) {
    const { params: { id } } = context;
    let res = await fetch(`https://dead-earrings-tick.cyclic.app/products/${id}`);
    let data = await res.json();
    console.log(data)
    return { props: { data } }
}